[package]
name = "play"
version = "0.1"
lean_version = "leanprover-community/lean:3.14.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "b2f643e9802e6e2a6aee5695d76ed03b55dd45a2"}
